# Generated by Django 3.1.3 on 2020-11-16 10:52

import CustomerInfo.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='customer',
            fields=[
                ('recordAdded', models.DateTimeField(auto_now_add=True)),
                ('recordModified', models.DateTimeField(auto_now=True)),
                ('customerId', models.CharField(default=CustomerInfo.models.generateUUID, editable=False, max_length=200, primary_key=True, serialize=False)),
                ('firstName', models.CharField(max_length=200)),
                ('lastName', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('mobileNo', models.CharField(max_length=15)),
                ('country', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
